import { test, expect } from "@playwright/test";
import { createClient } from "@libsql/client";
import { adminForProject } from "./admin-credentials";
test("comparison mutations require authorization", async ({ request }) => {
  for (const method of ["GET", "POST"]) expect((await request.fetch("/api/admin/comparisons", { method, data: {} })).status()).toBe(401);
  expect((await request.patch("/api/admin/comparisons/comparison-01", { data: { active: false } })).status()).toBe(401);
});
test("owner adds, edits, previews and deactivates localized comparisons", async ({ page }, info) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  const credentials = adminForProject(info.project.name);
  await page.goto("/en/admin/login");
  await page.locator("#admin-email").fill(credentials.email);
  await page.locator("#admin-password").fill(credentials.password);
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page).toHaveURL(/\/admin$/);
  expect((await page.request.post("/api/admin/comparisons", { data: {} })).status()).toBe(403);
  const csrf = (await (await page.request.get("/api/admin/session")).json()).csrfToken;
  expect((await page.request.post("/api/admin/comparisons", { headers: { "x-admin-csrf": csrf }, data: { name: "bad" } })).status()).toBe(400);
  await page.goto("/en/admin/gallery");
  const area = page.locator("section[aria-labelledby='admin-comparisons-title']");
  await area.getByRole("button", { name: "Add comparison", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Save", exact: true }).click();
  await expect(page.getByRole("dialog").getByRole("alert")).toBeVisible();
  const name = `QA comparison ${info.project.name}`, french = `Comparaison QA ${info.project.name}`;
  await page.locator("#comparisons-name").fill(name);
  await page.locator("#comparisons-nameFr").fill(french);
  await page.locator("#comparisons-description").fill("English comparison text.");
  await page.locator("#comparisons-descriptionFr").fill("Texte français de comparaison.");
  await page.locator("#comparisons-imageUrl").fill("/example-pics/hair-look-1.png");
  await page.locator("#comparisons-afterImageUrl").fill("/example-pics/hair-look-2.jpeg");
  await page.getByRole("dialog").getByRole("button", { name: "Save", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await area.getByLabel("Search", { exact: true }).fill(name);
  const row = area.locator("li").filter({ hasText: name });
  await row.getByRole("button", { name: "Preview", exact: true }).click();
  await expect(page.getByRole("dialog").getByRole("slider")).toBeVisible();
  await page.keyboard.press("Escape");
  await row.getByRole("button", { name: "Edit", exact: true }).click();
  await page.locator("#comparisons-name").fill(`${name} updated`);
  await page.locator("#comparisons-description").fill("Updated English text.");
  await page.locator("#comparisons-afterImageUrl").fill("/media/salon/caver1.webp");
  await page.getByRole("dialog").getByRole("button", { name: "Save", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.screenshot({ path: `artifacts/comparison-admin-${info.project.name}.png` });
  const records = (await (await page.request.get("/api/admin/comparisons")).json()).comparisons;
  const record = records.find((item: { name: string }) => item.name === `${name} updated`);
  expect(record.afterImageUrl).toBe("/media/salon/caver1.webp");
  const db = createClient({ url: process.env.E2E_DATABASE_URL! });
  const audit = await db.execute({ sql: "SELECT action FROM AuditLog WHERE targetId = ?", args: [record.id] });
  expect(audit.rows.map(r => r.action)).toEqual(expect.arrayContaining(["comparison.create", "comparison.update"])); db.close();
  for (const locale of ["en", "fr"]) {
    await page.goto(`/${locale}/gallery`);
    await expect(page.locator("#before-after")).toContainText(locale === "en" ? `${name} updated` : french);
    await expect(page.locator("#before-after")).toContainText(locale === "en" ? "Updated English text." : "Texte français de comparaison.");
  }
  await page.goto("/en/admin/gallery");
  await area.getByLabel("Search", { exact: true }).fill(name);
  await row.getByRole("button", { name: "Deactivate", exact: true }).click();
  await expect(row.getByRole("button", { name: "Activate", exact: true })).toBeVisible();
  await page.goto("/en/gallery"); await expect(page.locator("#before-after")).not.toContainText(name);
  await page.goto("/fr/admin/gallery");
  await area.getByRole("button", { name: "Ajouter un comparaison", exact: true }).click();
  await expect(page.getByRole("dialog").getByLabel("Image avant", { exact: true })).toBeVisible();
  await page.keyboard.press("Escape");
});
