import { logServerError } from "@/lib/safe-log";
import { readJsonBody } from "@/lib/request-body";
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { authorizeAdmin, authorizeAdminMutation } from "@/lib/admin-guard";
import { packagePatchSchema, flattenZodErrors } from "@/lib/validation";
import { writeAuditLog } from "@/lib/audit";
const include = { services: { include: { service: { select: { id: true, name: true, nameFr: true } } } }, images: { orderBy: { order: "asc" as const } } };
export async function GET(request: NextRequest, ctx: { params: Promise<{ id: string }> }) { const auth = await authorizeAdmin(request); if (!auth.ok) return auth.response; const { id } = await ctx.params; const row = await prisma.package.findUnique({ where: { id }, include }); return row ? NextResponse.json({ ok: true, package: row }) : NextResponse.json({ error: "NOT_FOUND", message: "Package not found." }, { status: 404 }); }
export async function PATCH(request: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const auth = await authorizeAdminMutation(request); if (!auth.ok) return auth.response; const { id } = await ctx.params; let body: unknown; try { body = await readJsonBody(request); } catch { return NextResponse.json({ error: "BAD_REQUEST", message: "Invalid JSON body" }, { status: 400 }); }
  const parsed = packagePatchSchema.safeParse(body); if (!parsed.success) return NextResponse.json({ error: "VALIDATION", fieldErrors: flattenZodErrors(parsed), message: "Please check the package details." }, { status: 400 }); const data = parsed.data;
  if (!(await prisma.package.findUnique({ where: { id }, select: { id: true } }))) return NextResponse.json({ error: "NOT_FOUND", message: "Package not found." }, { status: 404 });
  if (data.serviceIds && await prisma.service.count({ where: { id: { in: data.serviceIds } } }) !== data.serviceIds.length) return NextResponse.json({ error: "VALIDATION", fieldErrors: { serviceIds: "validation.service.required" } }, { status: 400 });
  try { const updated = await prisma.$transaction(async (tx) => { if (data.serviceIds) await tx.packageService.deleteMany({ where: { packageId: id } }); return tx.package.update({ where: { id }, data: { ...(data.name !== undefined && { name: data.name }), ...(data.nameFr !== undefined && { nameFr: data.nameFr }), ...(data.description !== undefined && { description: data.description || null }), ...(data.descriptionFr !== undefined && { descriptionFr: data.descriptionFr || null }), ...(data.price !== undefined && { price: data.price }), ...(data.sessions !== undefined && { sessions: data.sessions }), ...(data.validityDays !== undefined && { validityDays: data.validityDays ?? null }), ...(data.badge !== undefined && { badge: data.badge || null }), ...(data.imageUrl !== undefined && { imageUrl: data.imageUrl || null }), ...(data.active !== undefined && { active: data.active }), ...(data.order !== undefined && { order: data.order }), ...(data.serviceIds && { services: { create: data.serviceIds.map((serviceId) => ({ serviceId })) } }), ...(data.images && { images: { deleteMany: {}, create: data.images.map((image, order) => ({ ...image, order })) } }) }, include }); }); await writeAuditLog({ adminId: auth.session.adminId, action: "package.update", targetType: "Package", targetId: id, detail: Object.keys(data).join(", ") }); return NextResponse.json({ ok: true, package: updated }); } catch (error) { logServerError("admin package update error", error); return NextResponse.json({ error: "INTERNAL", message: "Something went wrong." }, { status: 500 }); }
}
export async function DELETE(request: NextRequest, ctx: { params: Promise<{ id: string }> }) { const auth = await authorizeAdminMutation(request); if (!auth.ok) return auth.response; const { id } = await ctx.params; const row = await prisma.package.findUnique({ where: { id }, select: { id: true, name: true } }); if (!row) return NextResponse.json({ error: "NOT_FOUND", message: "Package not found." }, { status: 404 }); await prisma.package.update({ where: { id }, data: { active: false } }); await writeAuditLog({ adminId: auth.session.adminId, action: "package.deactivate", targetType: "Package", targetId: id, detail: row.name }); return NextResponse.json({ ok: true }); }
